resolver: lts-17.14

packages:
- '.'
extra-deps:
- git: git://github.com/iokasimov/telega
  commit: b48bca01042b55d9bc230dc66ffd320148f8bc2a
- git: git://github.com/iokasimov/joint
  commit: b8446484c38ead0eb8bd351d685c6e3cc4ec09b0

flags: {}

extra-package-dbs: []

nix:
  enable: true
  shell-file: shell.nix
